### ISSUE TITLE
报无权限

### ISSUE THREAD

**Issue by shijianzhong** [TencentCloudBase/tcb-demo-avatar#2]
error:
Code: "AccessDenied"
Message: "Access Denied."
RequestId: "NWQ4YjI3MzdfNmMxZTFkMDlfNGMxXzE3NDNkNDA="
Resource: "avator-1250000.cos.ap-shanghai.myqcloud.com/generated/3673.png"
ServerTime: "2019-09-25T08:37:11Z"
TraceId: "OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjYjEzMGU3N2I0OTJjYTAwYWExNjJhODI1NTRkOGZlM2Y="
__proto__: Object
headers: {content-type: "application/xml", content-length: "510", connection: "close", date: "Wed, 25 Sep 2019 08:37:11 GMT", server: "tencent-cos", …}
statusCode: 403
__proto__: Object

**Comment by bestony** [comment]
看看你的 bucket、region、secret id 、secret 等是否匹配，是否有拼错的。

**Comment by shijianzhong** [comment]
已解决
